<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fontFamilies [
	<!ELEMENT fontFamilies (fontFamily)+>
	<!ELEMENT fontFamily (normal?, bold*, italic*, boldItalic*, pdfEncoding?, pdfEmbedded?)>
	<!ATTLIST fontFamily name CDATA #REQUIRED>
	<!ELEMENT normal (#PCDATA)>
	<!ELEMENT bold (#PCDATA)>
	<!ELEMENT italic (#PCDATA)>
	<!ELEMENT boldItalic (#PCDATA)>
	<!ELEMENT pdfEncoding (#PCDATA)>
	<!ELEMENT pdfEmbedded (#PCDATA)>
]>
<fontFamilies>

	<fontFamily name="Open Sans">
		<normal>id/co/tripoin/util/report/fonts/OpenSans/OpenSans-Regular.ttf</normal>
		<bold>id/co/tripoin/util/report/fonts/OpenSans/OpenSans-Bold.ttf</bold>
		<italic>id/co/tripoin/util/report/fonts/OpenSans/OpenSans-Italic.ttf</italic>
		<boldItalic>id/co/tripoin/util/report/fonts/OpenSans/OpenSans-BoldItalic.ttf</boldItalic>
		<pdfEncoding>Identity-H</pdfEncoding>
		<pdfEmbedded>true</pdfEmbedded>
	</fontFamily>

	<fontFamily name="Open Sans Light">
		<normal>id/co/tripoin/util/report/fonts/OpenSansLight/OpenSans-Light.ttf</normal>
		<italic>id/co/tripoin/util/report/fonts/OpenSansLight/OpenSans-LightItalic.ttf</italic>
		<pdfEncoding>Identity-H</pdfEncoding>
		<pdfEmbedded>true</pdfEmbedded>
	</fontFamily>

	<fontFamily name="Open Sans Semi Bold">
		<normal>id/co/tripoin/util/report/fonts/OpenSansSemiBold/OpenSans-Semibold.ttf</normal>
		<italic>id/co/tripoin/util/report/fonts/OpenSansSemiBold/OpenSans-SemiboldItalic.ttf</italic>
		<pdfEncoding>Identity-H</pdfEncoding>
		<pdfEmbedded>true</pdfEmbedded>
	</fontFamily>
	
</fontFamilies>
